# Generated by Django 3.2.5 on 2021-08-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('alternative_name', models.CharField(max_length=24)),
                ('bio', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('followers', models.IntegerField()),
                ('followed', models.IntegerField()),
                ('blocked', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=2000, null=True)),
                ('daily', models.BooleanField(blank=True, default=False)),
                ('day_of_week', models.CharField(default='[]', max_length=60)),
                ('time', models.TimeField()),
                ('edit_time', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('done', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='author', to='api.profile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follower', to='api.profile')),
            ],
        ),
    ]
