# Generated by Django 3.2.6 on 2021-08-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=24, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('profile', 'favorite_task')},
        ),
        migrations.AlterUniqueTogether(
            name='following',
            unique_together={('author', 'follower')},
        ),
    ]
