# Generated by Django 3.2.6 on 2021-08-25 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210825_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_task', to='api.task')),
            ],
        ),
    ]
